### ISSUE TITLE
How to combine this with react-router?

### ISSUE THREAD

**Issue by anjalikrishna** [aputinski/react-navigation-controller#1]
We would like to use this component. But no Idea how to make this work with react-router and make a page slider like, http://coenraets.org/samples/pageslider-react/index.html

**Comment by ccorcos** [comment]
+1

This exactly what I'm wondering. 

- How do we push a view but associate it with a route?
- How do we maintain scroll position of the component when popping back to a previous page?

**Comment by aputinski** [comment]
I primarily designed this component to be used in native web view apps, so URL support wasn't really a concern. If you have any suggestions for an API that would help with router integration, feel free to submit a PR.

**Comment by cserb** [comment]
@aputinski I think it makes sense to use it also in web apps that try to imitate native apps. Thus it would also make sense to support routes.
As I was playing with react native I realised that the UINavigationController idea might fit very well also for web apps and the first question that came to my mind was if I could use it with react-router :)

**Comment by aputinski** [comment]
Something like https://github.com/maisano/react-router-transition is probably a better fit if using `react-router`
