### ISSUE TITLE
Broken data-propagation

### ISSUE THREAD

**Issue by jvalle** [aputinski/react-navigation-controller#10]
Greetings,

I'm finding that the data-propagation is breaking when using an intermediate component to dynamically set the view.

I have code organized in the following way:

ParentComponent.jsx

```
render () {
 return (
    <Sidebar>
      <Component1 data={this.state.data} />
    </Sidebar>
  );
}
```

Sidebar.jsx

```
render () {
  const View = <div>{this.props.children}</div>;

  return <NavigationController views={[View]} />;
}
```

When `this.state.data` changes in `ParentComponent.jsx`, the rendered `Component1` doesn't update.

Should I regard this as intended behavior, or is there something that I can do to work around this use-case?

Thanks

**Comment by aputinski** [comment]
Unfortunately I think that's intended behavior for now because the controller stores the initial value of `views` in it's state. When I have some time (or if you do) I can look into seeing what would need to be changed to support this — it's quite possible that `views` doesn't need to be stored in the state at all and can just be referenced directly from the props.

**Comment by jvalle** [comment]
I ended up using the following work around, I'd be happy to formalize it into a PR, if you'd like:
```javascript
  __renderNextView() {
    const view = this.state.mountedViews[1];
    let newProps = {};
    if (!view) return null;
    this.props.views.forEach((v, i) => {
      if (view.key === v.key) {
	Object.keys(v.props).forEach(key => {
	  newProps[key] = v.props[key];
	});
      }
    });
    newProps.ref = `view-${this.__viewIndexes[1]}`;
    newProps.navigationController = this;
    return React.cloneElement(view, newProps);
  }
```
The only caveat, is that each child component passed to the NavigationController's View, will need to have its own unique `key` property, so that the `_renderNextView()` method knows which props to pass to which component.

This could probably be done with a little more efficiency, such as checking that the components' props have actually changed before propagating them, although I'm not totally convinced we should be concerned with that here (`shouldComponentUpdate` on the component itself).

**Comment by maxnowack** [comment]
I've ran into the same issue. A PR would be great 👍
