### ISSUE TITLE
Warning About Manually Calling React.PropTypes

### ISSUE THREAD

**Issue by jmstiles34** [aputinski/react-navigation-controller#12]
Warning: You are manually calling a React.PropTypes validation function for the `transition` prop on `pushView`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

Looks like its this line in the checkOptions function:

line 80: var e = optionType[[key]]((options, key, method, prop));

**Comment by aputinski** [comment]
Fixed by 2309dd3df0f018f6bd9db8dec9768c13ef9f94e7
