### ISSUE TITLE
Top view shifts down during navigation

### ISSUE THREAD

**Issue by kobble-git** [aputinski/react-navigation-controller#13]
If I push a new view left, the current view jumps down the height of the pushed view while the transition is in progress. It doesn't look right. I looked at the example, and they have special position:relative or absolute tags on some css elements. I tried those, but the absolute position won't work in my case. Is this special css required?

**Comment by aputinski** [comment]
Yeah, typically you would style `.ReactNavigationController` with `position:relative` with a fixed width/height and then `.ReactNavigationController` would be `position:absolute` so that the controller can animation the `translation` property.
