### ISSUE TITLE
Requires React 0.14?

### ISSUE THREAD

**Issue by ddoherty** [aputinski/react-navigation-controller#8]
Hi. Cool component.

I'm having an issue using it, and before I get into the details, I'll ask, does it require React 0.14?  I haven't yet upgraded my app from React 0.13, and wonder if this is the cause.

Thanks.

**Comment by aputinski** [comment]
Version `2.x` is compatible with React 0.13.

**Comment by ddoherty** [comment]
(which I would have seen had I just clicked on releases. jeez.)

Thanks.

**Comment by ddoherty** [comment]
Yep. That works (but you already knew that).

I look forward to giving it a spin.

Coming from the Cocoa Touch world, it looks like just what I am looking for.  

Thanks.
